// src/pages/Ddd/constants/widgetOptions.ts
export const widgetOptions = [
    { type: 'welcome', icon: 'fas fa-door-open', title: '환영합니다', description: '대학 ERP 시스템에 오신 것을 환영합니다.' },
    { type: 'notice', icon: 'fas fa-bullhorn', title: '공지사항', description: '학교 및 학과 공지사항 확인' },
    { type: 'lecture-note', icon: 'fas fa-book-open', title: '강의노트', description: '강의 자료 및 동영상 확인' },
    { type: 'library', icon: 'fas fa-book-reader', title: '도서관 좌석현황', description: '실시간 도서관 이용 정보' },
    { type: 'admin', icon: 'fas fa-cogs', title: '시스템관리자', description: '시스템 관리 및 설정' },
    { type: 'professor-contact', icon: 'fas fa-chalkboard-teacher', title: '교수한테 문의', description: '담당 교수님께 문의하기' },
    { type: 'grades', icon: 'fas fa-award', title: '성적 현황', description: '학기별 성적 확인' },
    { type: 'calendar', icon: 'fas fa-calendar-alt', title: '학사 일정', description: '다가오는 일정 확인' },
    { type: 'attendance', icon: 'fas fa-user-check', title: '출석 현황', description: '강의별 출석률 확인' },
    { type: 'assignments', icon: 'fas fa-tasks', title: '과제 현황', description: '제출해야 할 과제 확인' },
    { type: 'timetable', icon: 'fas fa-clock', title: '시간표', description: '오늘의 수업 일정' },
    { type: 'cafeteria', icon: 'fas fa-utensils', title: '학식 메뉴', description: '오늘의 학식 메뉴 확인' },
    { type: 'weather', icon: 'fas fa-cloud-sun', title: '캠퍼스 날씨', description: '오늘의 날씨 및 예보' },
    { type: 'bus', icon: 'fas fa-bus', title: '셔틀버스', description: '다음 버스 도착 시간' },
    { type: 'campus-map', icon: 'fas fa-map-marked-alt', title: '캠퍼스 맵', description: '캠퍼스 건물 위치 확인' },
    { type: 'scholarship', icon: 'fas fa-money-check-alt', title: '장학금 정보', description: '신청 가능한 장학금' },
    { type: 'tuition', icon: 'fas fa-wallet', title: '등록금 정보', description: '납부 내역 및 잔액' },
    { type: 'graduation', icon: 'fas fa-user-graduate', title: '졸업 요건', description: '졸업 요건 충족 현황' },
    { type: 'career', icon: 'fas fa-briefcase', title: '취업 정보', description: '채용 공고 및 설명회' },
    { type: 'health', icon: 'fas fa-heartbeat', title: '건강 관리', description: '건강검진 및 상담' },
    { type: 'club', icon: 'fas fa-users', title: '동아리 활동', description: '동아리 일정 및 공지' },
];
